export enum ErrorCode {
    INVALID_INPUT = "INVALID_INPUT",
    USER_EMAIL_OR_PHONE_EXISTS = "USER_EMAIL_OR_PHONE_EXISTS",
    USER_SIGNUP_FAILED = "USER_SIGNUP_FAILED",
    USER_LOGIN_FAILED = "USER_LOGIN_FAILED",
    UPDATE_USER_FAILED = "UPDATE_USER_FAILED",
    DELETE_USER_FAILED = "DELETE_USER_FAILED",
    NONEXISTENT_USER = "NONEXISTENT_USER",
    INVALID_EMAIL_OR_PASSWORD = "INVALID_EMAIL_OR_PASSWORD",
    CREATE_EVENT_FAILED = "CREATE_EVENT_FAILED",
    GET_EVENT_FAILED = "GET_EVENT_FAILED",
    GET_EVENTS_FAILED = "GET_EVENTS_FAILED",
    CREATE_RSVP_FAILED = "CREATE_RSVP_FAILED"
}